# Generated by Django 3.1.4 on 2021-03-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScPaths',
            fields=[
                ('path_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=40)),
                ('interval_time', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'sc_paths',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScresultsTest',
            fields=[
                ('var_title', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('value', models.FloatField(blank=True, null=True)),
                ('flag', models.IntegerField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'scresults_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'sc_users',
                'managed': False,
            },
        ),
    ]
