# Generated by Django 3.1.4 on 2021-03-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScConditions',
            fields=[
                ('cond_id', models.AutoField(primary_key=True, serialize=False)),
                ('v1', models.CharField(max_length=40)),
                ('v2', models.CharField(blank=True, max_length=40, null=True)),
                ('v3', models.CharField(blank=True, max_length=40, null=True)),
                ('v4', models.CharField(blank=True, max_length=40, null=True)),
                ('v5', models.CharField(blank=True, max_length=40, null=True)),
                ('formula', models.CharField(max_length=100)),
                ('cond_type', models.CharField(blank=True, max_length=15, null=True)),
                ('max_val', models.FloatField(blank=True, null=True)),
                ('min_val', models.FloatField(blank=True, null=True)),
                ('limit_val', models.FloatField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sc_conditions',
                'managed': False,
            },
        ),
    ]
