# Generated by Django 3.1.4 on 2021-05-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_scconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScConditionsResult',
            fields=[
                ('cond_id', models.IntegerField(primary_key=True, serialize=False)),
                ('val_result', models.FloatField(blank=True, null=True)),
                ('bool_result', models.IntegerField(blank=True, null=True)),
                ('val_formula', models.CharField(blank=True, max_length=1500, null=True)),
                ('result_formula', models.CharField(blank=True, max_length=1000, null=True)),
                ('time_calc', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sc_conditions_result',
                'managed': False,
            },
        ),
    ]
