# Generated by Django 3.1.4 on 2021-05-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_scconditionsresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScConditionsOnlweb',
            fields=[
                ('cond_id', models.AutoField(primary_key=True, serialize=False)),
                ('formula', models.CharField(max_length=250)),
                ('cond_type', models.CharField(blank=True, max_length=15, null=True)),
                ('max_val', models.CharField(max_length=250)),
                ('min_val', models.CharField(max_length=250)),
                ('limit_val', models.CharField(max_length=250)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('display_method', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'sc_conditions_onlweb',
                'managed': False,
            },
        ),
    ]
