# Generated by Django 3.1.4 on 2021-08-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_scconditionsonlweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScConditionsOnline',
            fields=[
                ('cond_id', models.AutoField(primary_key=True, serialize=False)),
                ('formula', models.CharField(max_length=250)),
                ('cond_type', models.CharField(blank=True, max_length=15, null=True)),
                ('max_val', models.CharField(max_length=250)),
                ('min_val', models.CharField(max_length=250)),
                ('limit_val', models.CharField(max_length=250)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('display_method', models.CharField(blank=True, max_length=10)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('isalert', models.IntegerField(blank=True, null=True)),
                ('alert_interval', models.IntegerField(blank=True, null=True)),
                ('time_create_or_alert', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sc_conditions_onlweb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScPathsOnline',
            fields=[
                ('path_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=100)),
                ('interval_time', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'sc_paths_online',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScResults',
            fields=[
                ('var_title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.FloatField(blank=True, null=True)),
                ('flag', models.IntegerField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'scresults_test',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ScConditionsOnlweb',
        ),
        migrations.DeleteModel(
            name='ScresultsTest',
        ),
    ]
