# Generated by Django 3.1.4 on 2021-08-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20210831_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScGraphInfo',
            fields=[
                ('dot_id', models.AutoField(primary_key=True, serialize=False)),
                ('dot_name', models.CharField(max_length=100)),
                ('dot_condition', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sc_graph_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScGraphName',
            fields=[
                ('graph_id', models.AutoField(primary_key=True, serialize=False)),
                ('graph_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sc_graph_name',
                'managed': False,
            },
        ),
    ]
