# Generated by Django 3.1.4 on 2021-11-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_scgraphinfo_scgraphname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScPostfixAutoCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('postfix_id', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'sc_postfix_auto_completion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScVariableAutoCompletion',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('postfix_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sc_variable_auto_completion',
                'managed': False,
            },
        ),
    ]
